import { marked } from "marked";
import { mkdir, readFile, readdir, writeFile } from "node:fs/promises";
import path from "node:path";

const siteRoot = process.cwd();
const repoRoot = path.resolve(siteRoot, "..");
const outputPath = path.join(siteRoot, "src", "generated", "docs.ts");

const sourceFiles = ["README.md", "CHANGELOG.md", ...(await markdownFiles(path.join(repoRoot, "docs")))];
const routeByFile = new Map(sourceFiles.map((file) => [normalizeDocPath(file), routeFromPath(file)]));

const sectionMap = [
  { test: /^README\.md$/, section: "Start", order: 10, summary: "Install, run, configure, and understand the project at a glance." },
  { test: /^docs\/completion\.md$/, section: "Start", order: 20, summary: "Current product-readiness state and known gaps." },
  { test: /^docs\/architecture\.md$/, section: "Concepts", order: 30, summary: "How requests move through listeners, policies, caches, balancers, and upstreams." },
  { test: /^docs\/adr\//, section: "Concepts", order: 40, summary: "Accepted architectural decisions and their consequences." },
  { test: /^docs\/configuration\.md$/, section: "Reference", order: 50, summary: "Strict YAML configuration fields, defaults, and validation behavior." },
  { test: /^docs\/compatibility\.md$/, section: "Reference", order: 60, summary: "Supported protocol paths, load balancer expectations, and explicit non-goals." },
  { test: /^docs\/deployment-/, section: "Deploy", order: 70, summary: "Production deployment baselines for Kubernetes, VMs, and bare metal." },
  { test: /^docs\/cloud-load-balancers\.md$/, section: "Deploy", order: 80, summary: "AWS, Google Cloud, and Azure load balancer operating notes." },
  { test: /^docs\/operations\.md$/, section: "Operate", order: 90, summary: "Daily operations, probes, reloads, shutdown, and diagnosis." },
  { test: /^docs\/runbooks\.md$/, section: "Operate", order: 100, summary: "Incident and upgrade procedures for real production events." },
  { test: /^docs\/production-transition\.md$/, section: "Operate", order: 110, summary: "Cutover evidence checklist before production traffic moves through Gefahr." },
  { test: /^docs\/disaster-recovery\.md$/, section: "Operate", order: 120, summary: "Recovery drills, evidence templates, RTO and RPO framing." },
  { test: /^docs\/security\.md$/, section: "Secure", order: 130, summary: "Security model, controls, and known limitations." },
  { test: /^docs\/release-acceptance\.md$/, section: "Release", order: 140, summary: "Release artifact, attestation, and acceptance requirements." },
  { test: /^CHANGELOG\.md$/, section: "Release", order: 150, summary: "Notable project changes by release." },
  { test: /^docs\/legacy-guide\//, section: "Learn", order: 200, summary: "Historical learning guide and implementation background." },
];

marked.use({
  gfm: true,
  breaks: false,
  mangle: false,
  headerIds: true,
});

const docs = [];
for (const file of sourceFiles) {
  const absolute = path.join(repoRoot, file);
  const markdown = await readFile(absolute, "utf8");
  const title = firstHeading(markdown) ?? titleFromPath(file);
  const headings = collectHeadings(markdown);
  const route = routeFromPath(file);
  const classification = classify(file);
  const html = await marked.parse(markdown, { renderer: rendererFor(file, route) });
  const plainText = toPlainText(markdown);
  docs.push({
    route,
    title,
    sourcePath: file,
    section: classification.section,
    sectionOrder: classification.order,
    summary: classification.summary ?? firstParagraph(markdown) ?? "",
    headings,
    readingMinutes: Math.max(1, Math.round(plainText.split(/\s+/).filter(Boolean).length / 220)),
    html,
    text: plainText,
  });
}

docs.sort((a, b) => a.sectionOrder - b.sectionOrder || a.title.localeCompare(b.title));

const sections = [...new Set(docs.map((doc) => doc.section))].map((section) => ({
  title: section,
  docs: docs.filter((doc) => doc.section === section).map((doc) => doc.route),
}));

await mkdir(path.dirname(outputPath), { recursive: true });
await writeFile(
  outputPath,
  `/* This file is generated by scripts/generate-docs.mjs. */\n` +
    `export type DocPage = {\n` +
    `  route: string;\n  title: string;\n  sourcePath: string;\n  section: string;\n  sectionOrder: number;\n  summary: string;\n  headings: string[];\n  readingMinutes: number;\n  html: string;\n  text: string;\n};\n\n` +
    `export type DocSection = { title: string; docs: string[] };\n\n` +
    `export const docs: DocPage[] = ${JSON.stringify(docs, null, 2)};\n\n` +
    `export const sections: DocSection[] = ${JSON.stringify(sections, null, 2)};\n`,
);

async function markdownFiles(directory) {
  const entries = await readdir(directory, { withFileTypes: true });
  const files = [];
  for (const entry of entries) {
    const absolute = path.join(directory, entry.name);
    if (entry.isDirectory()) {
      files.push(...(await markdownFiles(absolute)));
    } else if (entry.isFile() && entry.name.endsWith(".md")) {
      files.push(path.relative(repoRoot, absolute));
    }
  }
  return files.sort();
}

function classify(file) {
  return sectionMap.find((entry) => entry.test.test(file)) ?? { section: "Reference", order: 500, summary: undefined };
}

function firstHeading(markdown) {
  const match = markdown.match(/^#\s+(.+)$/m);
  return match?.[1].trim();
}

function collectHeadings(markdown) {
  return [...markdown.matchAll(/^#{2,3}\s+(.+)$/gm)].map((match) => match[1].trim()).slice(0, 8);
}

function firstParagraph(markdown) {
  const withoutTitle = markdown.replace(/^#\s+.+$/m, "");
  const paragraphs = withoutTitle.split(/\n{2,}/).map((value) => value.trim());
  return paragraphs.find((value) => value && !value.startsWith("|") && !value.startsWith("```") && !value.startsWith("- "))?.replace(/\n/g, " ");
}

function titleFromPath(file) {
  return path
    .basename(file, ".md")
    .replace(/^\d+-/, "")
    .replace(/[-_]/g, " ")
    .replace(/\b\w/g, (letter) => letter.toUpperCase());
}

function routeFromPath(file) {
  if (file === "README.md") {
    return "start/overview";
  }
  if (file === "CHANGELOG.md") {
    return "release/changelog";
  }
  return file
    .replace(/^docs\//, "")
    .replace(/\.md$/, "")
    .toLowerCase()
    .replace(/[^a-z0-9/]+/g, "-")
    .replace(/\/index$/, "");
}

function rendererFor(sourceFile, sourceRoute) {
  const renderer = new marked.Renderer();
  renderer.link = function ({ href, title, tokens }) {
    const text = this.parser.parseInline(tokens);
    const rewritten = rewriteLink(sourceFile, sourceRoute, href);
    const safeTitle = title ? ` title="${escapeHtml(title)}"` : "";
    const data = rewritten.anchor ? ` data-doc-anchor="${escapeHtml(rewritten.anchor)}"` : "";
    return `<a href="${escapeHtml(rewritten.href)}"${safeTitle}${data}>${text}</a>`;
  };
  return renderer;
}

function rewriteLink(sourceFile, sourceRoute, href) {
  if (!href || /^(https?:|mailto:|tel:)/i.test(href)) {
    return { href };
  }
  if (href.startsWith("#")) {
    return { href: `#/${sourceRoute}`, anchor: href.slice(1) };
  }
  const [target, anchor] = href.split("#", 2);
  const withoutQuery = target.split("?")[0];
  if (!withoutQuery.endsWith(".md")) {
    return { href };
  }
  const sourceDirectory = path.dirname(sourceFile);
  const normalized = normalizeDocPath(path.normalize(path.join(sourceDirectory, withoutQuery)));
  const route = routeByFile.get(normalized);
  if (!route) {
    return { href };
  }
  return { href: `#/${route}`, anchor };
}

function normalizeDocPath(file) {
  return file.replaceAll(path.sep, "/").replace(/^\.\//, "");
}

function escapeHtml(value) {
  return value
    .replaceAll("&", "&amp;")
    .replaceAll("<", "&lt;")
    .replaceAll(">", "&gt;")
    .replaceAll('"', "&quot;");
}

function toPlainText(markdown) {
  return markdown
    .replace(/```[\s\S]*?```/g, " ")
    .replace(/`([^`]+)`/g, "$1")
    .replace(/!\[[^\]]*]\([^)]+\)/g, " ")
    .replace(/\[([^\]]+)]\([^)]+\)/g, "$1")
    .replace(/^#{1,6}\s+/gm, "")
    .replace(/[*_>|#-]/g, " ")
    .replace(/\s+/g, " ")
    .trim();
}
