import { marked } from "marked";
import { mkdir, readFile, readdir, writeFile } from "node:fs/promises";
import path from "node:path";

const siteRoot = process.cwd();
const repoRoot = path.resolve(siteRoot, "..");
const contentRoot = path.join(siteRoot, "content");
const outputPath = path.join(siteRoot, "src", "generated", "docs.ts");

const sourceFiles = await markdownFiles(contentRoot);
const routeByFile = new Map(sourceFiles.map((file) => [normalizeDocPath(file), routeFromPath(file)]));

marked.use({
  gfm: true,
  breaks: false,
  mangle: false,
  headerIds: true,
});

const docs = [];
for (const file of sourceFiles) {
  const absolute = path.join(siteRoot, file);
  const raw = await readFile(absolute, "utf8");
  const { frontmatter, markdown } = parseFrontmatter(raw);
  const title = frontmatter.title ?? firstHeading(markdown) ?? titleFromPath(file);
  const headings = collectHeadings(markdown);
  const route = routeFromPath(file);
  const html = await marked.parse(markdown, { renderer: rendererFor(file, route) });
  const plainText = toPlainText(markdown);
  docs.push({
    route,
    title,
    sourcePath: path.posix.join("gefahr-docs", normalizeDocPath(file)),
    section: frontmatter.section ?? "Reference",
    sectionOrder: Number(frontmatter.order ?? 500),
    summary: frontmatter.summary ?? firstParagraph(markdown) ?? "",
    headings,
    readingMinutes: Math.max(1, Math.round(plainText.split(/\s+/).filter(Boolean).length / 220)),
    html,
    text: plainText,
  });
}

docs.sort((a, b) => a.sectionOrder - b.sectionOrder || a.title.localeCompare(b.title));

const sections = [...new Set(docs.map((doc) => doc.section))].map((section) => ({
  title: section,
  docs: docs.filter((doc) => doc.section === section).map((doc) => doc.route),
}));

await mkdir(path.dirname(outputPath), { recursive: true });
await writeFile(
  outputPath,
  `/* This file is generated by scripts/generate-docs.mjs. */\n` +
    `export type DocPage = {\n` +
    `  route: string;\n  title: string;\n  sourcePath: string;\n  section: string;\n  sectionOrder: number;\n  summary: string;\n  headings: string[];\n  readingMinutes: number;\n  html: string;\n  text: string;\n};\n\n` +
    `export type DocSection = { title: string; docs: string[] };\n\n` +
    `export const docs: DocPage[] = ${JSON.stringify(docs, null, 2)};\n\n` +
    `export const sections: DocSection[] = ${JSON.stringify(sections, null, 2)};\n`,
);

async function markdownFiles(directory) {
  const entries = await readdir(directory, { withFileTypes: true });
  const files = [];
  for (const entry of entries) {
    const absolute = path.join(directory, entry.name);
    if (entry.isDirectory()) {
      files.push(...(await markdownFiles(absolute)));
    } else if (entry.isFile() && entry.name.endsWith(".md")) {
      files.push(normalizeDocPath(path.relative(siteRoot, absolute)));
    }
  }
  return files.sort();
}

function firstHeading(markdown) {
  const match = markdown.match(/^#\s+(.+)$/m);
  return match?.[1].trim();
}

function collectHeadings(markdown) {
  return [...markdown.matchAll(/^#{2,3}\s+(.+)$/gm)].map((match) => match[1].trim()).slice(0, 8);
}

function firstParagraph(markdown) {
  const withoutTitle = markdown.replace(/^#\s+.+$/m, "");
  const paragraphs = withoutTitle.split(/\n{2,}/).map((value) => value.trim());
  return paragraphs.find((value) => value && !value.startsWith("|") && !value.startsWith("```") && !value.startsWith("- "))?.replace(/\n/g, " ");
}

function titleFromPath(file) {
  return path
    .basename(file, ".md")
    .replace(/^\d+-/, "")
    .replace(/[-_]/g, " ")
    .replace(/\b\w/g, (letter) => letter.toUpperCase());
}

function routeFromPath(file) {
  return file
    .replace(/^content\//, "")
    .replace(/\.md$/, "")
    .toLowerCase()
    .replace(/[^a-z0-9/]+/g, "-")
    .replace(/\/index$/, "");
}

function parseFrontmatter(raw) {
  if (!raw.startsWith("---\n")) {
    return { frontmatter: {}, markdown: raw };
  }
  const end = raw.indexOf("\n---\n", 4);
  if (end === -1) {
    return { frontmatter: {}, markdown: raw };
  }
  const frontmatter = {};
  for (const line of raw.slice(4, end).split("\n")) {
    const separator = line.indexOf(":");
    if (separator === -1) continue;
    const key = line.slice(0, separator).trim();
    const value = line.slice(separator + 1).trim();
    frontmatter[key] = value.replace(/^["']|["']$/g, "");
  }
  return { frontmatter, markdown: raw.slice(end + 5).trimStart() };
}

function rendererFor(sourceFile, sourceRoute) {
  const renderer = new marked.Renderer();
  renderer.link = function ({ href, title, tokens }) {
    const text = this.parser.parseInline(tokens);
    const rewritten = rewriteLink(sourceFile, sourceRoute, href);
    const safeTitle = title ? ` title="${escapeHtml(title)}"` : "";
    const data = rewritten.anchor ? ` data-doc-anchor="${escapeHtml(rewritten.anchor)}"` : "";
    return `<a href="${escapeHtml(rewritten.href)}"${safeTitle}${data}>${text}</a>`;
  };
  return renderer;
}

function rewriteLink(sourceFile, sourceRoute, href) {
  if (!href || /^(https?:|mailto:|tel:)/i.test(href)) {
    return { href };
  }
  if (href.startsWith("#/")) {
    return { href };
  }
  if (href.startsWith("#")) {
    return { href: `#/${sourceRoute}`, anchor: href.slice(1) };
  }
  const [target, anchor] = href.split("#", 2);
  const withoutQuery = target.split("?")[0];
  if (!withoutQuery.endsWith(".md")) {
    return { href };
  }
  const sourceDirectory = path.dirname(sourceFile);
  const normalized = normalizeDocPath(path.normalize(path.join(sourceDirectory, withoutQuery)));
  const route = routeByFile.get(normalized);
  if (!route) {
    return { href };
  }
  return { href: `#/${route}`, anchor };
}

function normalizeDocPath(file) {
  return file.replaceAll(path.sep, "/").replace(/^\.\//, "");
}

function escapeHtml(value) {
  return value
    .replaceAll("&", "&amp;")
    .replaceAll("<", "&lt;")
    .replaceAll(">", "&gt;")
    .replaceAll('"', "&quot;");
}

function toPlainText(markdown) {
  return markdown
    .replace(/```[\s\S]*?```/g, " ")
    .replace(/`([^`]+)`/g, "$1")
    .replace(/!\[[^\]]*]\([^)]+\)/g, " ")
    .replace(/\[([^\]]+)]\([^)]+\)/g, "$1")
    .replace(/^#{1,6}\s+/gm, "")
    .replace(/[*_>|#-]/g, " ")
    .replace(/\s+/g, " ")
    .trim();
}
